version: 0.19.{build}
clone_folder: c:\gopath\src\github.com\mackerelio\mackerel-agent
environment:
  GOPATH: c:\gopath
install:
  - set PATH=c:\go\bin;c:\tools\ruby215\bin;%PATH%
  - echo %Path%
  - choco install ruby
  - rd c:\go /s /q
  - cinst mingw-get
  - set PATH=%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin
  - mingw-get install mingw-developer-toolkit
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.3.3.windows-amd64.zip
  - 7z x go1.3.3.windows-amd64.zip -oC:\ >nul
  - go version
  - go env
  - env
build_script:
- call wix\build.bat
test_script:
- FOR /F "usebackq" %%w IN (`git rev-parse --show-cdup`) DO SET CDUP=%%w
- cd %CDUP%
- go get -d -v -t ./...
- go vet ./...
- go test -short ./...
notifications:
  - provider: Slack
    auth_token:
      secure: A7QmXiJAvb+wWfCyBXGCDmKpe7mEDywYI7Ai1LLEi8NNAssCJusGjCpHNv7KiRZz
    channel: mackerel
deploy:
  release: $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token:
    secure: nT6f+l3sILrBAyVGLE1il+wkv5BvrnEnVkiPGDZQegePa81MUC4AIDTNQ/gX8AWW
  artifact: mackerel-agent-msi
  appveyor_repo_tag: true
  on:
    appveyor_repo_tag: true
artifacts:
  - path: build\mackerel-agent.msi
    name: mackerel-agent-msi
