version: 0.14.{build}
clone_folder: c:\gopath\src\github.com\mackerelio\mackerel-agent
environment:
  GOPATH: c:\gopath
install:
  - set PATH=c:\go\bin;c:\tools\ruby215\bin;%PATH%
  - echo %Path%
  - choco install ruby
  - rd c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.4.1.windows-amd64.zip
  - 7z x go1.4.1.windows-amd64.zip -oC:\ >nul
  - go version
  - go env
  - env
build_script:
- call wix\build.bat
test_script:
- FOR /F "usebackq" %%w IN (`git rev-parse --show-cdup`) DO SET CDUP=%%w
- cd %CDUP%
- go get -d -v -t ./...
- go vet ./...
- go test -short ./...
notifications:
  - provider: Slack
    auth_token:
      secure: g8kxcFTMRU9m64NhA1rzBZaPY72haF7+3t3T0NL/Mug00izQ4B1FjhoHbTQPUVGT
    channel: mackerel
deploy:
  release: $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token:
    secure: 2HLHAjVNhpeABGoWAe6iqAtEeq4fjawUVsGq4aBF4yOQsF67IOqBOh8NYHqq25yM
  artifact: mackerel-agent-msi
  draft: true
  prerelease: true
  appveyor_repo_tag: true
  on:
    appveyor_repo_tag: true
artifacts:
  - path: build\mackerel-agent.msi
    name: mackerel-agent-msi
